# Generated by Django 4.1.2 on 2022-10-12 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car_wash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.carwash'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='phone_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
